const constants = {
    ADD_DAY: "ADD_DAY",
    REMOVE_DAY: "REMOVE_DAY",
    SET_GOAL: "SET_GOAL",
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    FETCH_RESORT_NAMES: "FETCH_RESORT_NAMES",
    CACHE_RESORT_NAMES: "CACHE_RESORT_NAMES",
    CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
    CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS",
    CANCEL_FETCHING: "CANCEL_FETCHING"
}

export default constants